# Generated by Django 6.0.6 on 2026-06-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.CharField(max_length=10)),
                ('diretor', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('nota', models.FloatField()),
                ('poster', models.URLField(blank=True)),
            ],
        ),
    ]
